// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siwrhstxdfbdhufotjzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpd3Joc3R4ZGZiZGh1Zm90anp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NzE0NjQsImV4cCI6MjA1NjM0NzQ2NH0.03UvfemNaa1qQ-VWRp7_urHsPpaH0rUA10YpaePeUxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);